# -*- coding: utf-8 -*-
"""DS_EXP5.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k5m7bVaAORI8cV9fCIv-SE7b-G7Py-nY
"""

from pickle import NEWOBJ_EX
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score


dataset =pd.read_csv('/content/Salary_data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,1].values
print(dataset.head())



x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/3,random_state=0)
regressor = LinearRegression()
regressor.fit(x_train, y_train)

plt.scatter(x_train,y_train,color='red',label='Actual')
plt.plot(x_train, regressor.predict(x_train), color='blue', label='predicted')
plt.title('Salary VS \Experience')
plt.xlabel('year of Expeience')
plt.ylabel('Salary')
plt.legend()
plt.show()

plt.scatter(x_test,y_test ,color='red',label='Actual')
plt.plot(x_train, regressor.predict(x_train), color='blue', label='predicted')
plt.title('Salary VS Experience(Test set)')
plt.xlabel('year of Expeience')
plt.ylabel('Salary')
plt.legend()
plt.show()

y_pred=regressor.predict(x_test)
y_pred

mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print("Mean squared error(mse)",mse)
print("root mean squarred error(rmse)",rmse)
print("Mean absolute error(mae)",mae)
print("r squarred(r2)",r2 )

new_input=[[5]]
y_pred = regressor.predict(new_input)
print("Predicted salary :",y_pred)